#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=0,1,2,3 PYTORCH_JIT=0 NCCL_LL_THRESHOLD=0 python \
-W ignore \
-i \
-m torch.distributed.launch \
--master_port=9984 \
--nproc_per_node=4 \
main.py \
--network_feature resnet18 \
--dataset hollywood2 \
--batch_size 32 \
--img_dim 128 \
--epochs 100 \
--pred_step 0 \
--seq_len 5 \
--num_seq 6 \
--lr 1e-3 \
--prefix earlyaction_linear_hollywood2_euclidean_64d \
--fp16 \
--pretrain logs/log_finetune_earlyaction_euclidean_poincare_hollywood2_64d_fromhypermovienet/20201110_104834/model/model_best_epoch17.pth.tar  \
--linear_input predictions_z_hat \
--n_classes 17 \
--use_labels \
--num_workers 15 \
--only_train_linear \
--early_action \
--num_workers 8 \
--seed 0 \
--action_level_gt \
--hierarchical_labels \
--feature_dim 64 \
--path_dataset /proj/vondrick/datasets/Hollywood2/
