python main.py \
--gpu 4,5,6,7 \
--net resnet18 \
--dataset k600 \
--batch_size 64 \
--img_dim 80 \
--epochs 300 \
--start-epoch 0 \
--reset_lr \
--hyperbolic hyperbolic1 \
--lr 1e-3 \
--prefix hyperbolic1_nopretrain
