#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=6,7 PYTORCH_JIT=0 NCCL_LL_THRESHOLD=0 python \
-W ignore \
-i \
-m torch.distributed.launch \
--master_port=9997 \
--nproc_per_node=2 \
main.py \
--pred_step 1 \
--hyperbolic \
--hyperbolic_version 1 \
--distance squared \
--network_feature resnet18 \
--dataset finegym \
--seq_len 5 \
--num_seq 6 \
--ds 3 \
--batch_size 32 \
--img_dim 128 \
--epochs 200 \
--fp16 \
--fp64_hyper \
--num_workers 15 \
--lr 0.01 \
--prefix finetune_earlyaction_self_hyper_v1_poincare_finegym_2dim_nospatial \
--cross_gpu_score \
--early_action \
--early_action_self \
--pretrain logs/log_finetune_earlyaction_self_hyper_v1_poincare_finegym_2dim/20201103_135631/model/model_best_epoch5.pth.tar \
--final_2dim \
--no_spatial \
--path_dataset /proj/vondrick/datasets/FineGym \
--resume logs/log_finetune_earlyaction_self_hyper_v1_poincare_finegym_2dim_nospatial/20201104_104814/model/epoch5.pth.tar
