python main.py \
--gpu 0,1,2,3 \
--net resnet18 \
--dataset hollywood2 \
--batch_size 64 \
--img_dim 80 \
--epochs 600 \
--hyperbolic \
--hyperbolic_version 1 \
--early_action \
--early_action_self \
--pred_step 1 \
--distance 'squared' \
--lr 1e-3 \
--prefix hyperbolic_hollywood2_v1_earlyaction_selfsupervised_squared_lr3